**

!Data-Intelligence-SDK/
Data-Intelligence-SDK/**
!Data-Intelligence-SDK/pyproject.toml
!Data-Intelligence-SDK/uv.lock
!Data-Intelligence-SDK/README.md
!Data-Intelligence-SDK/configs/
!Data-Intelligence-SDK/configs/**
!Data-Intelligence-SDK/packages/
Data-Intelligence-SDK/packages/**
!Data-Intelligence-SDK/packages/sdk/
!Data-Intelligence-SDK/packages/sdk/pyproject.toml
!Data-Intelligence-SDK/packages/sdk/src/
!Data-Intelligence-SDK/packages/sdk/src/**
!Data-Intelligence-SDK/packages/api/
!Data-Intelligence-SDK/packages/api/pyproject.toml
!Data-Intelligence-SDK/packages/api/src/
!Data-Intelligence-SDK/packages/api/src/**

!AXIOM/
AXIOM/**
!AXIOM/packages/
AXIOM/packages/**
!AXIOM/packages/axiom-sandbox-client/
!AXIOM/packages/axiom-sandbox-client/**
!AXIOM/packages/axiom-model-client/
!AXIOM/packages/axiom-model-client/**
